application: s~emu-1964
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /blog
  static_dir: blog

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /lib
  static_dir: lib

- url: /shaders
  static_dir: shaders

- url: /roms/unofficial
  static_dir: roms/unofficial

- url: /.*
  script: 1964js.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
